/* Generated By:JJTree: Do not edit this line. ASTAssignmentOperator.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;
import parser.ssParser;
public
class ASTAssignmentOperator extends SimpleNode {
  public ASTAssignmentOperator(int id) {
    super(id);
  }

  public ASTAssignmentOperator(ssParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ssParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0e9af954faba96387fffb11dd8d18966 (do not edit this line) */
