/*Q2*/
SELECT DISTINCT PHONE , L_name AS FamilyName from FAMILYPACKAGE, RECCENTERMEMBER where 
FAMILYPACKAGE.ID = 
(SELECT DISTINCT Family_id FROM RECCENTERMEMBER WHERE L_name = 'O’Shea') AND
RECCENTERMEMBER.L_name = 'O’Shea';

/*Q3*/
SELECT DISTINCT F_NAME，L_NAME FROM RECCENTERMEMBER, ENROLLMENT WHERE RECCENTERMEMBER.ID = ENROLLMENT.Member_ID 
AND ENROLLMENT.COST = (SELECT MAX(COST) FROM ENROLLMENT);

/*Q4*/
SELECT INSTRUCTOR.F_NAME as First_Name, INSTRUCTOR.L_NAME as Last_name FROM INSTRUCTOR WHERE
MEMBER_ID is null;

/*Q5*/
SELECT F_NAME AS FIRST_NAME ,L_Name as last_name FROM RECCENTERMEMBER WHERE RECCENTERMEMBER.ID IN
(SELECT DISTINCT ENROLLMENT.MEMBER_ID FROM ENROLLMENT 
GROUP BY ENROLLMENT.MEMBER_ID
HAVING COUNT (*)>=3 );

/*Q6*/
Select F_NAME AS FIRST_NAME ,L_Name as last_name FROM RECCENTERMEMBER WHERE RECCENTERMEMBER.ID IN 
(SELECT DISTINCT ENROLLMENT.MEMBER_ID FROM ENROLLMENT
WHERE ENROLLMENT.CLASS_ID IN (Select CLASS.ID FROM CLASS WHERE TYPE = 'Craft')
);

/*Q7*/
SELECT F_NAME AS FIRST_NAME ,L_Name as last_name FROM RECCENTERMEMBER WHERE 
DOB > to_date('01/01/1950','MM/DD/YYYY') AND DOB < to_date('01/01/1980','MM/DD/YYYY');

/*Q8*/
SELECT DISTINCT CLASS.TYPE,TYPE.Description FROM CLASS ,TYPE WHERE CLASS.YEAR IN (2008 , 2009) AND CLASS.TYPE = TYPE.TYPE;


